#!/bin/bash

cleanrepo() {
    echo "The repo isn't clean, please stash or commit your changes and try again." >&2
    exit 2
}

git stash -q --keep-index
[[ -z "$(git status --porcelain)" ]] || cleanrepo

ROOT_DIR="$(dirname "$0")/.."
source "${ROOT_DIR}/scripts/constants.sh"

./gradlew check ${GRADLE_PARALLEL} ${GRADLE_LOG_LEVEL}
RESULT=$?

git stash pop -q
exit ${RESULT}