#!/bin/bash

source "$(dirname "$0")/constants.sh"

set -eu
set -o pipefail

if [[ $(docker-machine ls -q --filter="name=${DOCKER_MACHINE_NAME}" | wc -l | awk '{print $1}') -eq 0 ]]; then
    echo "creating virtual machine ${DOCKER_MACHINE_NAME}"
    docker-machine create -d=virtualbox --virtualbox-memory 2048 ${DOCKER_MACHINE_NAME}
fi

echo "creating bootsync for ${DOCKER_MACHINE_NAME} docker-machine..."
DOCKER_HOST_IP=$(docker-machine ip ${DOCKER_MACHINE_NAME})
docker-machine ssh ${DOCKER_MACHINE_NAME} "sudo cat > /tmp/bootsync.sh" <<-BOOTSYNC
#!/bin/sh
grep '\-\-dns' /var/lib/boot2docker/profile || {
        echo "EXTRA_ARGS=\"\$EXTRA_ARGS --dns ${DOCKER_HOST_IP} --dns 10.160.11.21 --dns 10.160.11.22 --dns 10.100.11.21 --dns 10.100.11.22\"" | sudo tee -a /var/lib/boot2docker/profile
}
echo -e "nameserver 10.160.11.21\nnameserver 10.160.11.22\nnameserver 10.100.11.21\nnameserver 10.100.11.22" | sudo tee /etc/resolv.conf
BOOTSYNC
docker-machine ssh ${DOCKER_MACHINE_NAME} "sudo mv /tmp/bootsync.sh /var/lib/boot2docker/bootsync.sh"
echo

docker-machine restart ${DOCKER_MACHINE_NAME}
echo

LOCAL_RESOLVER_PATH="$(dirname "$0")/resolver-bfl.conf"
SYSTEM_RESOLVER_PATH=/etc/resolver/bfl
echo "Setting up name server ${DOCKER_HOST_IP} in ${SYSTEM_RESOLVER_PATH} (enter sudo password when promoted)"
echo "nameserver ${DOCKER_HOST_IP}" > ${LOCAL_RESOLVER_PATH}
sudo ln -s ${LOCAL_RESOLVER_PATH} ${SYSTEM_RESOLVER_PATH}
