#!/bin/bash

set -eu
set -o pipefail

ROOT_DIR="$(dirname "$0")/.."
source "${ROOT_DIR}/scripts/constants.sh"

usage() {
    echo "Usage: $0 docker-env [start|stop]" >&2
    echo >&2
    exit 1
}

[[ $# == 1 ]] || usage

DOCKER_HOST_IP=$(docker-machine ip ${DOCKER_MACHINE_NAME})
eval "$(docker-machine env ${DOCKER_MACHINE_NAME})"

case $1 in
    start)
        docker-compose -f ${ROOT_DIR}/docker/nameserver.yml -p nameserver up -d
        docker-compose -f ${ROOT_DIR}/docker/docker-compose.yml --x-networking -p bitflow up -d
        ;;

    stop)
        docker-compose -f ${ROOT_DIR}/docker/docker-compose.yml -p bitflow stop
        ;;

    *) usage ;;
esac