#!/bin/bash

set -euo pipefail

usage() {
    echo "Usage: $0 docker-env [start|stop]" >&2
    echo >&2
    exit 1
}

[[ $# == 1 ]] || usage

ROOT_DIR="$(dirname "$0")/.."
source "${ROOT_DIR}/scripts/constants.sh"

# if we're on a Mac, we need to make sure we're running the correct docker-machine
if [ "$(uname)" == "Darwin" ]; then
    DOCKER_HOST_IP=$(docker-machine ip ${DOCKER_MACHINE_NAME})
    eval "$(docker-machine env ${DOCKER_MACHINE_NAME})"
fi

case $1 in
    start)
        docker-compose -f ${ROOT_DIR}/docker/nameserver.yml -p nameserver up -d
        docker-compose -f ${ROOT_DIR}/docker/docker-compose.yml -p bitflow up -d
        ;;

    stop)
        docker-compose -f ${ROOT_DIR}/docker/docker-compose.yml -p bitflow stop
        ;;

    *) usage ;;
esac