#!/bin/bash

set -euo pipefail
set -x

ROOT_DIR="$(dirname "$0")/.."
GRADLEW_OPTS="--parallel --max-workers 4 --stacktrace --profile --console=plain"
source "${ROOT_DIR}/scripts/constants.sh"

if [[ -z ${CIRCLE_NODE_INDEX+x} ]]; then    # running locally
    WORKER_INDEX=0
    TOTAL_WORKERS=1
else                                        # running in CircleCI
    WORKER_INDEX=${CIRCLE_NODE_INDEX}
    TOTAL_WORKERS=${CIRCLE_NODE_TOTAL}
fi

pushd $(dirname $0)/.. > /dev/null
if [[ ${WORKER_INDEX} -eq $((0 % ${TOTAL_WORKERS})) ]]; then
    ./gradlew ${GRADLEW_OPTS} check
fi

if [[ ${WORKER_INDEX} -eq $((1 % ${TOTAL_WORKERS})) ]]; then
    ./gradlew ${GRADLEW_OPTS} docker -x bitflow-docker-base:docker dockerComposeUp
    docker run -it \
      -w /workspace \
      --net=${DOCKER_COMPOSE_NETWORK} \
      -v /home/ubuntu/.gradle:/root/.gradle/ \
      -v $(pwd):/workspace \
      -e TERM=dumb \
      daedalus2718/bitflow-base:latest \
      ./gradlew ${GRADLEW_OPTS} integrationTests -x dockerComposeUp
fi

popd > /dev/null
