#!/bin/bash

set -eu
set -o pipefail
#set -x # for temporary debugging

usage() {
    echo "Usage: $0 (pruned|full)" >&2
    echo >&2
    exit 1
}

[[ $# == 1 || $# == 2 ]] || usage

# set some things we use in a few places below
pushd `dirname $0` > /dev/null
ROOT_DIR=`pwd -P`
popd > /dev/null
BITCOIND_IMAGE=daedalus2718/bitcoind
CONTAINER_BITCOIN_HOME=/data/bitcoin
CONTAINER_BITCOIN_CONF="${CONTAINER_BITCOIN_HOME}/bitcoin.conf"
BITCOIND_USER=bitcoin
LOCAL_BITCOIN_CONF="${ROOT_DIR}/conf/current-bitcoin.conf"
LOCAL_DATA_VOLUME_DIR=/data/bitcoin

# load the RPC creds
source "${ROOT_DIR}/conf/rpc.properties"

# always pull remote images to avoid caching issues
if [ -z "${BITCOIND_IMAGE##*/*}" ]; then
   docker pull "${BITCOIND_IMAGE}"
fi 

# create local configuration file from template with pruned or full node params
case $1 in
    pruned)
        cat "${ROOT_DIR}/conf/pruned-node.conf" \
            "${ROOT_DIR}/conf/common.conf" > "${LOCAL_BITCOIN_CONF}" ;;

    full)
        cat "${ROOT_DIR}/conf/full-node.conf" \
            "${ROOT_DIR}/conf/common.conf" > "${LOCAL_BITCOIN_CONF}" ;;

    *) usage ;;
esac

# kill and remove any existing containers
docker kill bitcoind-data bitcoind-node 2>/dev/null || true
docker rm bitcoind-data bitcoind-node 2>/dev/null || true
#stop docker-bitcoind 2>/dev/null || true # for upstart script (not defined yet)

# run data container
# N.B., whatever data exists in LOCAL_DATA_VOLUME_DIR will be mounted into CONTAINER_BITCOIN_HOME
docker run --name=bitcoind-data 
    -v "${LOCAL_DATA_VOLUME_DIR}:${CONTAINER_BITCOIN_HOME}" "${BITCOIND_IMAGE}" \
    chown "${BITCOIND_USER}:${BITCOIND_USER}" -R "${CONTAINER_BITCOIN_HOME}"

# copy over local bitcoin.conf and make bitcoin user own it (this is kind of a hack b/c can't figure
# out how to mount config file via -v with proper bitcoin user ownership)
docker cp "${LOCAL_BITCOIN_CONF}" bitcoind-data:"${CONTAINER_BITCOIN_CONF}"
docker run --volumes-from=bitcoind-data --rm "${BITCOIND_IMAGE}" \
    chown "${BITCOIND_USER}:${BITCOIND_USER}" "${CONTAINER_BITCOIN_CONF}"

# run the Docker container
docker run --name=bitcoind-node --volumes-from=bitcoind-data --rm -u "${BITCOIND_USER}" \
    -p 8333:8333 \
    -p 127.0.0.1:8332:8332 \
    -e BITCOIND_RPCUSER="${RPCUSER}" \
    -e BITCOIND_RPCPASSWORD="${RPCPASSWORD}" \
    "${BITCOIND_IMAGE}"